### ISSUE TITLE
Slow Loading Time due to the Video & All the photos in the about us section

### ISSUE THREAD

**Issue by divyansh-pathak129** [kushagra-a-singh/I.R.I.S-PROD#4]
The initial loading time of the website is very slow because of the video & the multiple images that are present in the about us
In order to fix it, we can replace the video with a gradient and then upload the photos on s3 or supabase storage and then insert the photo's link.. That will drastically reduce the loading time

**Comment by IRIS-MITWPU** [comment]
can we make a test version and verrify this ?
also , we plan on making a amazon S3 instance for this site as a server so we need to do this as well 

just to correct  , supabase will only support as a DB , postgres DB to be specific .
We need to host a server to be very precise 
Good suggest tho!

**Comment by divyansh-pathak129** [comment]
not really a server but we need to upload the photos to a storage and fetch the photo via the link like I have done in the Carousel... The website will load faster because the frontend will load before the pictures
Also we can do this with anything.... S3, Supabase storage or any object storage service to fetch the files...

**Comment by TakshDhabalia** [comment]
Well a server will be the most optimal solution but I am not sure about the supabase storage part but a server will be the most useful for us in this scenario .
@kushagra-a-singh @24Hoshiko can we try it out this month ?

**Comment by kushagra-a-singh** [comment]
yes, we can setup an s3 instance and configure our backend totally on the server side. For the meantime, we can use supabase carousel for members page.
